services:
  - type: web
    name: iaags
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run streamlit_app.py --server.headless true --server.address 0.0.0.0 --server.port $PORT
